export const HOME_OG_IMAGE_URL = "";
export const SITE_DESCRIPTION = "";
export const SITE_NAME = "Git masters";
export const SITE_AUTHOR = "Ali Heydari";
export const SITE_AUTHOR_TWITTER_ID = "Ali4Heydari";
export const SITE_AUTHOR_FACEBOOK_ID = "Ali4Heydari";
export const SITE_AUTHOR_INSTAGRAM_ID = "Ali4Heydari";
export const SITE_AUTHOR_LINKEDIN_ID = "Ali4Heydari";
export const PUBLIC_URL = "/";
